### ISSUE TITLE
Ошибка при переходе к оплате

### ISSUE THREAD

**Issue by nickitatkach** [begateway/magento2-payment-module#1]
Добрый день.

Добавил bePaid к своему интернет-магазину. При переходе к оплате появляется вот такая ошибка из логов:

"Fatal Error: 'Uncaught Error: Class 'beGateway\Settings' not found in /home/zruchnab/public_html/app/code/BeGateway/BeGateway/Model/Config.php:71\nStack trace:\n#0 /home/zruchnab/public_html/app/code/BeGateway/BeGateway/Model/Method/Checkout.php(272): BeGateway\BeGateway\Model\Config->initGatewayClient()\n#1 /home/zruchnab/public_html/generated/code/BeGateway/BeGateway/Model/Method/Checkout/Interceptor.php(50): BeGateway\BeGateway\Model\Method\Checkout->order(Object(Magento\Sales\Model\Order\Payment\Interceptor), 25)\n#2 /home/zruchnab/public_html/vendor/magento/module-sales/Model/Order/Payment/Operations/OrderOperation.php(35): BeGateway\BeGateway\Model\Method\Checkout\Interceptor->order(Object(Magento\Sales\Model\Order\Payment\Interceptor), 25)\n#3 /home/zruchnab/public_html/vendor/magento/module-sales/Model/Order/Payment/Processor.php(97): Magento\Sales\Model\Order\Payment\Operations\OrderOperation->order(Object(Magento\Sales\Model\Order\Payment\Interceptor), 25)\n#4 /home/zruchnab/public_html/vendor/magento/module-sales/Mode' in '/home/zruchnab/public_html/app/code/BeGateway/BeGateway/Model/Config.php' on line 71"

Использую Magento 2.3

Спасибо

**Comment by webcreative24** [comment]
@nickitatkach Утановите API lib для работы с платежной системой через composer 
`composer require begateway/begateway-api-php 4.2.1`
